### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by gabn88** [radriaanse/docker-machine-driver-pcextreme#6]
I'm using:

`docker-machine create -d cloudstack --cloudstack-api-url https://api.auroracompute.eu/ams   --cloudstack-api-key SECRET   --cloudstack-secret-key SECRET --cloudstack-template "ubuntu 18.10" --cloudstack-zone zone01.ams02 --cloudstack-service-offering "Agile|1G" --cloudstack-expunge docker-machine`

But I get the error that there are 2 possible templates... I tried all possible additional info (20GB, etc) but cannot get it to work. Also entered the IDs of the PCextreme portal (by looking into the network requests I could figure them out) but entering them also doesn't work...

**Comment by radriaanse** [comment]
Hi,

There are some issues with using the generic Cloudstack driver on the PCextreme cloud, that's why this one exists as a (temporary) solution.

You can build the current version from master and run something similar as above like:
```
docker-machine create \
        --driver pcextreme \
        --pcextreme-api-key="" \
        --pcextreme-secret-key="" \
        --pcextreme-template="Ubuntu 18.10" \
        --pcextreme-ssh-user="ubuntu" \
        --pcextreme-service-offering="Agile | 4G" \
        ubuntu01
```

This should get you an Ubuntu 18.10 vm in the default region+zone (Amsterdam zone01.ams02).
Some inconveniences are still here, such as the zone naming, but this should get reworked soon after which I'll update this driver to implement those changes.

**Comment by gabn88** [comment]
Thank you!
